### ISSUE TITLE
Add cr.spec.hostname

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/console-operator#36]
Currently `hostname` is defaulted, but the user should be able to add a hostname.

If a `hostname` is provided, then a cert for the hostname should also be provided.

**Comment by wking** [comment]
Is this `spec.hostname` or (to match [`RouteSpec.Host`][1]), `spec.host`?  On the custom-host front, it looks like the operator has been switching on `RouteSpec.Host` to monitor route liveness since ef4e933a6360a (currently [here][2]).  But it would be nice to have the operator set this to avoid the current `console-openshift-console` name chosen by [this origin logic][3].  `openshift-console.{shard.DNSSuffix}` seems less redundant and still sufficiently unique (we won't have other routes from this namespace, and even if we do, they'll be less use-facing, right?).  I looked briefly into working up a PR, but I wasn't sure how to get `shard.DNSSuffix`, or even the cluster domain, to feed into `DefaultRoute`, and I didn't want to put in the time if it would only be breaking some status-monitoring logic.

[1]: https://github.com/openshift/api/blob/31ed61683850951801cddda5b075fcb24a500532/route/v1/types.go#L68-L72
[2]: https://github.com/openshift/console-operator/blame/37991a619ba244c2c9204f84a1b8262a24f19725/pkg/console/operator/sync_v400.go#L270
[3]: https://github.com/openshift/origin/blob/3434ddaa102995e2555a15f46ecaa6831832c026/pkg/route/allocation/simple/plugin.go#L51-L52

**Comment by wking** [comment]
> ... or even the cluster domain...

@Miciah points out that this is available from the ingress.config.openshift/io/cluster object.

**Comment by benjaminapetersen** [comment]
Well, this issue should be closed, we are not allowing a custom hostname for 4.0, at least not out the gate.

But you bring up an interesting point (that I can transfer to a Jira if we want to do it).  

Essentially, the generated route:
```
// is a little silly
https://console-openshift-console.apps.bpeterse.devcluster.openshift.com/
// and could be better
https://console-openshift.apps.bpeterse.devcluster.openshift.com/
```
Correct?

**Comment by wking** [comment]
> Essentially, the generated route...

Yes, all of that.

**Comment by benjaminapetersen** [comment]
Created a JIRA . https://jira.coreos.com/browse/CONSOLE-1249

**Comment by benjaminapetersen** [comment]
Closing this issue in favor of Jira.
Thanks!

**Comment by eyenx** [comment]
Hi 

We don't have access to the Jira. What is the status on this? Is it somehow possible to change the default [servicename]-[namespace] subdomain default?

**Comment by spadgett** [comment]
Unfortunately, not yet. The console hostname is not configurable in 4.1.
